// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9pUDaab9PbF7y9wAGiUlCzE272-jdPmc',
    appId: '1:1074043418572:web:f6c0daeb65bc998d768f69',
    messagingSenderId: '1074043418572',
    projectId: 'e-learning-2da6f',
    authDomain: 'e-learning-2da6f.firebaseapp.com',
    storageBucket: 'e-learning-2da6f.appspot.com',
    measurementId: 'G-ZQVW3TJHC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBEFTzUADbpgMckcK49LNsRAjnPAxxQ88',
    appId: '1:1074043418572:android:8e08eb9e17046e7c768f69',
    messagingSenderId: '1074043418572',
    projectId: 'e-learning-2da6f',
    storageBucket: 'e-learning-2da6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSlCj3VxBO8X3EtzSxqwo_kkstvSYH8ds',
    appId: '1:1074043418572:ios:9d7bf8d9881fe3e3768f69',
    messagingSenderId: '1074043418572',
    projectId: 'e-learning-2da6f',
    storageBucket: 'e-learning-2da6f.appspot.com',
    iosBundleId: 'com.example.eLearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9pUDaab9PbF7y9wAGiUlCzE272-jdPmc',
    appId: '1:1074043418572:web:afee38d4325286fa768f69',
    messagingSenderId: '1074043418572',
    projectId: 'e-learning-2da6f',
    authDomain: 'e-learning-2da6f.firebaseapp.com',
    storageBucket: 'e-learning-2da6f.appspot.com',
    measurementId: 'G-SFSBYXDREY',
  );
}
