// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9pUDaab9PbF7y9wAGiUlCzE272-jdPmc',
    appId: '1:1074043418572:web:f42d62c7c054a315768f69',
    messagingSenderId: '1074043418572',
    projectId: 'e-learning-2da6f',
    authDomain: 'e-learning-2da6f.firebaseapp.com',
    storageBucket: 'e-learning-2da6f.appspot.com',
    measurementId: 'G-G62LK3MS61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBEFTzUADbpgMckcK49LNsRAjnPAxxQ88',
    appId: '1:1074043418572:android:225e935e3fdb6583768f69',
    messagingSenderId: '1074043418572',
    projectId: 'e-learning-2da6f',
    storageBucket: 'e-learning-2da6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSlCj3VxBO8X3EtzSxqwo_kkstvSYH8ds',
    appId: '1:1074043418572:ios:2787135cf881e0bc768f69',
    messagingSenderId: '1074043418572',
    projectId: 'e-learning-2da6f',
    storageBucket: 'e-learning-2da6f.appspot.com',
    iosBundleId: 'com.example.eLearning',
  );
}
